### ISSUE TITLE
How to install fluent-ffmpeg in AWS Lamdba?

### ISSUE THREAD

**Issue by isaacp0310** [fluent-ffmpeg/node-fluent-ffmpeg#1069]
### Version information

* fluent-ffmpeg version: ^2.1.2
* ffmpeg version or build: ffmpeg-git-20190925-amd64-static.tar.xz
* OS:  Lambda (Linux enviroment) / Node 12.x

### Code to reproduce

Hi, can you help how did you set up the library in the lambda function correctly?

Because i already set up the:

-Serverless file with it's layer
-Uploaded the binaries to the lambda function as a layer
-Already set up the FFPROBE_PATH AND FFMPEG_PATH from the lambda function

**Also the weird thing is that: the lambda function just finish working, like sending a response.**
![image](https://user-images.githubusercontent.com/35440957/95387637-ff99a580-08be-11eb-9fc9-1498aea2e2c1.png)

**I mean also if you could show me step by step how did you installed it in a lambda function?**

* You will see the following example of how i have everything setup and it stills does not work

**1- This is from the lambda console**
![image](https://user-images.githubusercontent.com/35440957/95386867-ee03ce00-08bd-11eb-91ae-29b45bd90471.png)

![image](https://user-images.githubusercontent.com/35440957/95386217-f60f3e00-08bc-11eb-9fd8-b51d1b04a81e.png)

**2- My json dependencies**

```
 "dependencies": {
    "aws-sdk": "^2.764.0",
    "aws-serverless-express": "^3.3.8",
    "fluent-ffmpeg": "^2.1.2",
    "lambduh-execute": "^1.3.0"
  }
```
**3- My serverless file**

```
`service: functionName

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 3008
  timeout: 300
  stage: live
  region: us-east-1
  environment:
    FFMPEG_PATH: /opt/ffmpeg/ffmpeg
    FFPROBE_PATH: /opt/ffmpeg/ffprobe

functions:
  api:
    handler: lambda.handler
    events:
      - s3: ${self:custom.bucket}
    layers:
      - { Ref: FfmpegLambdaLayer }

layers:
  ffmpeg:
    path: layer

custom:
  bucket: buckename

```

**4- The directory of the layer**

![image](https://user-images.githubusercontent.com/35440957/95386502-6918b480-08bd-11eb-95e6-1b0b78f3a230.png)

**5- Javascript file**
```

const fs = require("fs");
const AWS = require("aws-sdk");
const ffmpeg = require("fluent-ffmpeg");
const s3 = new AWS.S3();

exports.handler = async (event, context, callback) => {

ffmpeg({
        source: `**Object file which i already verified it exists**`,
        nolog: true,
      })
        .on("filenames", async (filenames) => {
          console.log("Uploading please wait");
        })
        .on("error", function (err) {
          console.log("Error in filenames section: " + JSON.stringify(err));
        })
        .on("end", function () {
          console.log("Screenshots taken");
        })
        .screenshots({
          count: 10,
          folder: "tmp/",
          filename: "thumbnail-at-%i.png",
          size: "1600x900",
        })
        .on("end", function (stdout, stderr) {
          let destparams = {
            Bucket: dstBucket,
            Key: imageGotoUrl,
            Body: buffer,
            ContentType: "image",
          };

        })
        .on("error", function (err) {
          console.log("Error writing video to disk: " + JSON.stringify(err));
          throw "An error: " + err.message;
        });

};

```

### Expected results
The dependecy must work as expected in a AWS lambda function.

### Observed results
Lambda function just finish it's job without showing any log (Error) messages
In the cloudwatch console it just show the log that lambda finished de function succesfully (Not the expected from the dependency)

**I already used this dependecy locally, and it works! but in LAMBDA it is too hard**

### Checklist

* [ X] I have read the [FAQ](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/FAQ)
* [ X] I have included full stderr/stdout output from ffmpeg
* [ X] I have included the binaries from the static build and deployed it to the lambda function
* [ X] I have set the enviroment variables
 FFMPEG_PATH: /opt/ffmpeg/ffmpeg
 FFPROBE_PATH: /opt/ffmpeg/ffprobe
